
stages:
  - test
  - build_base
  - build
  - deploy

variables:
  CACHE_REGISTRY: docker.app.knihovny.cz
  TARGET_REGISTRY: registry.app.knihovny.cz
  BUILD_IMAGE: "docker.app.knihovny.cz/ci-builds/buildah"
  BASE_IMAGE_NAME: moravianlibrary/registrace-php
  IMAGE_NAME: moravianlibrary/registrace
  BUILDAH_LAYERS: 'true'

Test the code:
  stage: test
  only:
    refs:
      - master
      - /^devel/
      - merge_requests
  script:
    - echo "OK"

Build base image:
  stage: build_base
  image: "${BUILD_IMAGE}"
  only:
    refs:
      - master
      - /^devel/
      - merge_requests
    changes:
      - .gitlab-ci.yml
      - build/php-image/*
      - build/php-image/**/*
  cache:
    key: '${CI_PROJECT_NAME}'
    paths:
      - .cache
    policy: pull-push
  before_script:
    - mkdir -p .cache
    # try to load image from cache registry
    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${BASE_IMAGE_NAME}:latest ; then echo Cache loaded 1>&2 ; fi
    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${BASE_IMAGE_NAME}:build ; then echo Cache loaded 1>&2 ; fi
  script:
    - cd ${CI_PROJECT_DIR}
    # build the image
    - buildah build-using-dockerfile --layers -t ${BASE_IMAGE_NAME}:${CI_COMMIT_REF_SLUG} -f- build/php-image < build/php-image/Dockerfile
    # push image to Target Registry (on push)
    - if ( $CI_PIPELINE_SOURCE == 'push' ); then
            buildah push --format v2s2 ${BASE_IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker://${TARGET_REGISTRY}/${BASE_IMAGE_NAME}:${CI_COMMIT_REF_SLUG};
      fi

Build app image:
  stage: build
  image: "${BUILD_IMAGE}"
  variables:
    IMAGE_CACHE_FILE: "${CI_PROJECT_DIR}/.cache/${CI_PROJECT_PATH_SLUG}.tar"
  only:
    refs:
      - master
      - /^devel/
      - merge_requests
  before_script:
    - mkdir -p .cache
    # try to load image from cache registry
    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${BASE_IMAGE_NAME}:latest ; then echo Cache loaded 1>&2 ; fi
    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${BASE_IMAGE_NAME}:build ; then echo Cache loaded 1>&2 ; fi
  script:
    - cd ${CI_PROJECT_DIR}
    # build the image
    - buildah build-using-dockerfile --layers -t ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} -f- . < build/app/Dockerfile
    # push image to Target Registry (on git push or merge)
    - buildah push --format v2s2 ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker://${TARGET_REGISTRY}/${IMAGE_NAME}:build
    - if [ $CI_PIPELINE_SOURCE == 'push' ]; then
            buildah push --format v2s2 ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker://${TARGET_REGISTRY}/${IMAGE_NAME}:env-${CI_COMMIT_REF_SLUG} ;
            buildah push --format v2s2 ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker://${TARGET_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} ;
      fi

Deploy devel image:
  stage: build
  only:
    refs:
      - /^devel/
  script:
    - echo OK

Deploy master image:
  stage: build
  only:
    refs:
      - master
      - main
  script:
    - echo OK
