
services:
  registration:
    image: moravianlibrary/registrace/app:build
    command: "apache"
    ports:
      - "8080:80"
      - "8117:8117"
    volumes:
      - ./web/:/var/www/

  shibboleth:
    image: moravianlibrary/registrace/app:build
    command: "shibboleth"
    environment:
      MEMCACHED_SERVICE: "memcached:11211"
    depends_on:
      - memcached
    network_mode: 'service:registration'

  memcached:
    image: docker.io/library/memcached:1.6.9
    mem_limit: 64M
    ports:
      - "127.0.0.1:11211:11211"
