version: "2"

services:
  registration:
    image: moravianlibrary/registrace/app:build
    command: "apache"
    ports:
     - "8080:80"
     - "8117:8117"
    volumes:
     - ./web/:/var/www/
    environment:
      SHIBSP_LISTENER_ADDRESS: 'shibboleth'
      SHIBSP_LISTENER_PORT: '1600'

  shibboleth:
    image: moravianlibrary/registrace/app:build
    command: "shibboleth"
    ports:
     - "1600:1600"
