<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('title_registration')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MBZGH4');</script>
        <!-- /Google Tag Manager -->

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/flag-icon.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-select.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/i18n/defaults-cs_CZ.min.js'))
            ->prependFile($this->basePath('js/bootstrap-select.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
    </head>
    <body>
        <!-- Google Tag Manager (noscript) -->
        <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MBZGH4" height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
        <!-- /Google Tag Manager (noscript) -->

        <header>
            <div class="container">
                <a href="/" title="<?=$this->translate('logo_title')?>" rel="home" class="logo d-inline-block align-middle">
                    <img src="<?=$this->basePath('img/logo-mzk-white.svg')?>" alt="<?=$this->translate('logo_title')?>">
                </a>
                <div class="h1 d-inline-block align-middle"><?=$this->translate('head_text')?></div>
                <div class="float-right">
                    <a href="/?lang=cs" title="Česky">
                        <span class="flag-icon flag-icon-cs"></span>
                    </a>
                    <a href="/?lang=en" title="English">
                        <span class="flag-icon flag-icon-en"></span>
                    </a>
                </div>
            </div>
        </header>
        <div class="content">
            <?= $this->content ?>
        </div>
        <footer>
            <div class="container">
                <div class="media logo-footer">
                    <div class="media-header">
                        <a href="/" title="<?=$this->translate('logo_title')?>">
                            <img style="max-width: 150px; min-width: 150px;" src="<?=$this->basePath('img/logo-mzk-white.svg')?>" alt="<?=$this->translate('logo_title')?>">
                        </a>
                    </div>
                    <div class="media-body">
                        <p class="small mb-0">
                            <?=$this->translate('footer_text')?>
                        </p>
                        <p class="small mb-0">
                            <a class="text-muted" href="https://www.mzk.cz/registration_mzk" title="Původní předregistrace nových čtenářů">Původní předregistrace</a>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>
