<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Registration')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
    </head>
    <body>
        <div class="header">
            <div class="container-fluid">
                <a href="/" title="(Moravská zemská knihovna - úvodní stránka)" rel="home" class="logo d-inline-block align-middle">
                    <img src="<?=$this->basePath('img/logo-mzk-white.svg')?>" alt="Moravská zemská knihovna - úvodní stránka">
                    </a>
                <div class="h1 d-inline-block align-middle">Registrace čtenáře</div>
                </div>
                </div>
        <div class="content">
            <?= $this->content ?>
        </div>
        <footer>
            <div class="container-fluid">
                <img src="<?=$this->basePath('img/logo-mzk-white.svg')?>" alt="Moravská zemská knihovna - úvodní stránka" style="width: 138px;">
            </div>
        </footer>
    </body>
</html>
