<?php
/**
* @var \Laminas\Form\Element|\Laminas\Form\Element\DateSelect $element
*/
?>
<? if ($element instanceof \Laminas\Form\Element): ?>
    <? if ($element instanceof \Laminas\Form\Element\DateSelect): ?>
        <?php
        $options = $element->getOptions();
        $required = isset($options['required']) && $options['required'];
        $element->setLabelAttributes(['class' => 'form-label']);

        $elementClass = 'form-control';
        $readonly = $element->getAttribute('readonly');
        if ($readonly) {
            $elementClass .= ' readonly';
        }
        if (!empty($element->getMessages())) {
            $elementClass .= ' is-invalid';
        }
        $dayElement = $element->getDayElement()
            ->setAttribute('class', $elementClass);

        $monthElement = $element->getMonthElement()
            ->setAttribute('class', $elementClass);

        $yearElement = $element->getYearElement()
            ->setAttribute('class', $elementClass);
        ?>
        <div class="form-group">
            <label class="form-label<?= $required ? ' required' : '' ?><?= $readonly ? ' readonly' : '' ?>" for="<?= $element->getName() ?>">
                <?=$this->translate($element->getLabel()); ?>:<?= $required ? '*' : null ?>
            </label>
            <?php if($element->hasAttribute('data-help-icon')): ?>
                <span class="help-context" data-toggle="popover" data-placement="top" data-content="<?= $this->translate($element->getAttribute('data-help-icon'))?>">
                    <i class="fa fa-question-circle text-muted" aria-hidden="true"></i>
                </span>
            <?php endif ?>
            <div class="form-inline">
                <div class="form-group">
                    <div>
                        <? $this->formElement($element) //@todo to fill elements with options ?>
                        <?=$this->formElement($dayElement) ?>
                        <?=$this->formElement($monthElement) ?>
                        <?=$this->formElement($yearElement) ?>
                    </div>
                    <?=$this->formElementErrors()->render($element, ['class' => 'form-text error']) ?>
                </div>
            </div>
        </div>

    <? elseif ($element instanceof \Laminas\Form\Element\Checkbox): ?>
        <?php
        $elementClass = 'form-check-input';
        if (!empty($element->getMessages())) {
            $elementClass .= ' is-invalid';
        }
        $element
            ->setLabelAttributes(['class' => 'form-check-label'])
            ->setAttribute('class', $elementClass)
            ->setAttribute('id', $element->getName());
        ?>
        <div class="form-group form-check">
            <?=$this->formElement($element)?>
            <?=$this->formLabel($element)?>
            <?php if($element->hasAttribute('data-help-icon')): ?>
                <span class="help-context" data-toggle="popover" data-placement="top" data-content="<?= $this->translate($element->getAttribute('data-help-icon'))?>">
                    <i class="fa fa-question-circle text-muted" aria-hidden="true"></i>
                </span>
            <?php endif ?>
            <?php if($element->hasAttribute('data-help')): ?>
                <small class="form-text text-muted"><?= $this->translate($element->getAttribute('data-help'))?></small>
            <?php endif; ?>
        </div>

    <? else: ?>
        <?php
        $options = $element->getOptions();
        $labelClass = 'form-label';
        $required = (isset($options['required']) && $options['required']) || ($element->getAttribute('fake_required') ?? false);
        $element->setLabelAttributes(['class' => $labelClass]);
        $class = 'form-control';
        if ($element->getAttribute('readonly')) {
            $class .= ' readonly';
        }
        if (!empty($element->getMessages())) {
            $class .= ' is-invalid';
        }
        $element->setAttribute('class', $class);
        $element->setAttribute('id', $element->getName());
        ?>
        <div class="form-group<?= $required ? ' required' : '' ?>">
            <?//= $this->formLabel($element) ?>
            <label class="form-label<?= $required ? ' required' : '' ?>" for="<?= $element->getName() ?>">
                <?=$this->translate($element->getLabel()); ?>:<?= $required ? '*' : null ?>
            </label>
            <?php if($element->hasAttribute('data-help-icon')): ?>
                <span class="help-context" data-toggle="popover" data-placement="top" data-content="<?= $this->translate($element->getAttribute('data-help-icon'))?>">
                    <i class="fa fa-question-circle text-muted" aria-hidden="true"></i>
                </span>
            <?php endif ?>
            <?= $this->formElement($element) ?>
            <?php if($element->hasAttribute('data-help')): ?>
                <small class="form-text text-muted"><?= $this->translate($element->getAttribute('data-help'))?></small>
            <?php endif; ?>
            <?=$this->formElementErrors()->render($element, ['class' => 'form-text error']) ?>
        </div>
    <? endif; ?>
<? endif; ?>
