<?php
    $discount = $this->discount;
    $online = $discount['online'];
    $price = $discount['price'];
    $paymentLink = ($online && $price > 0);
?>
<div>
    <? if (!$this->verified): ?>
        <p>
            <?= $this->translate('preregistration_finished') ?>
        </p>
    <? else: ?>
        <p>
            <?= $this->translate('registration_finished') ?>
        </p>
    <? endif; ?>
    <p>
        <?= $this->translate('registration_login_text') ?> <?= $this->escapeHtml($this->login); ?>
    </p>
    <? if ($paymentLink): ?>
        <p>
            <?= $this->translate('payment_amount_text') ?>
            <?= $this->escapeHtml($price) ?>
            <?= $this->translate('payment_amount_currency') ?>
        </p>
        <p>
            <a href="/payment/init"><?= $this->translate('registration_online_payment_text') ?> </a>
        </p>
    <? endif; ?>
</div>

<hr>

<div>
    <p class="text-muted"><i>Text pro další krok při možnosti platby online:</i></p>

    <p>
        Gratulujeme!<br>
        Právě jste si založili čtenářský účet v Moravské zemské knihovně.
    </p>
    <div class="alert alert-primary">
        Dočasný login pro vaše přihlášení do účtu je <strong>XVNPUHO</strong>, po vydání průkazky se login změní.
    </div>
    <p>
        Na základě vámi vyplněných údajů činí roční registrační poplatek: <strong>xxx&nbsp;Kč</strong>
    </p>

    <div class="row my-4">
        <div class="col-md-6 text-center">
            <a class="btn btn-info" href="#" title="Platba kartou">
                <i class="fa fa-credit-card mr-1" aria-hidden="true"></i>
                Zaplatit kartou online
            </a>
        </div>
        <div class="col-md-6 text-center">
            <a class="btn btn-info" href="/Payment/finishedCash" title="Platba v hotovosti">
                <i class="fa fa-money mr-1" aria-hidden="true"></i>
                Zaplatím v hotovosti v knihovně
            </a>
        </div>
    </div>

    <p>
        Něco je špatně, částka nesedí? <a href="#" title="Zpět na vyplnění formuláře">Vraťte se zpět k formuláři.</a>
    </p>
    <p>
        Vaše knihovna
    </p>
    <p>
        Kontakt: <a href="mailto: pujcovna@mzk.cz" title="E-mail pujcovna@mzk.cz">pujcovna@mzk.cz</a>, tel.: 541 646 207
    </p>

</div>

<hr>

