<div class="page-index">

    <section>
        <div class="container">
            <?=$this->flashMessenger()->render();?>

            <h2 class="supertitle"><?=$this->translate('homepage_h1')?> <img src="<?=$this->basePath('img/logo-mzk-sign.svg')?>" alt="<?=$this->translate('homepage_h1_img_alt')?>">?</h2>
            <div class="row">
                <div class="col-sm-12 col-md-7 pt-4">

                    <ul class="list-tips">
                        <li>
                            <i class="fa fa-2x fa-check-circle text-success"></i>
                            <span><?=$this->translate('info_item_1')?></span>
                        </li>
                        <li>
                            <i class="fa fa-2x fa-check-circle text-success"></i>
                            <span><?=$this->translate('info_item_2')?></span>
                        </li>
                        <li>
                            <i class="fa fa-2x fa-check-circle text-success"></i>
                            <span><?=$this->translate('info_item_3')?></span>
                        </li>
                        <li>
                            <i class="fa fa-2x fa-check-circle text-success"></i>
                            <span><?=$this->translate('info_item_4')?></span>
                        </li>
                    </ul>

                    <div>
                        <a class="btn btn-success text-uppercase" href="#registration">
                            <?=$this->translate('btn_goto_registration')?>
                        </a>
                        <a class="btn btn-link" href="https://vufind.mzk.cz/Shibboleth.sso/Login?target=https%3A%2F%2Fvufind.mzk.cz%2FMyResearch%2FHome%3Fauth_method%3DShibboleth">
                            <?=$this->translate('btn_signin_existing')?>
                        </a>
                    </div>

                </div>
                <div class="col-md-5 d-none d-md-block d-lg-block d-xl-block">
                    <img src="<?=$this->basePath('img/home.png')?>" alt="">
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <ul class="list-tips-small">
                <li>
                    <i class="fa fa-couch"></i>
                    <span><?=$this->translate('benefit_item_2')?></span>
                </li>
                <li>
                    <i class="fa fa-book"></i>
                    <span><?=$this->translate('benefit_item_1')?></span>
                </li>
                <li>
                    <i class="fa fa-tablet-alt"></i>
                    <span><?=$this->translate('benefit_item_7')?></span>
                </li>
                <li>
                    <i class="fa fa-laptop"></i>
                    <span><?=$this->translate('benefit_item_3')?></span>
                </li>
                <li>
                    <i class="fa fa-users"></i>
                    <span><?=$this->translate('benefit_item_4')?></span>
                </li>
                <li>
                    <i class="fa fa-newspaper"></i>
                    <span><?=$this->translate('benefit_item_5')?></span>
                </li>
                <li class="mb-0">
                    <i class="fa fa-wifi"></i>
                    <span><?=$this->translate('benefit_item_6')?></span>
                </li>
            </ul>
        </div>
    </section>

    <section class="select-registration" id="registration">
        <div class="container">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 g-5">

                <!-- MZK -->
                <div class="col text-center mb-3">
                    <div class="card h-100 border-0 rounded-pill card-mzk">
                        <div class="card-body">
                            <h2 class="heading-logo mt-0"><img src="<?=$this->basePath('img/logo-mzk.svg')?>" alt="<?=$this->translate('box_mzk_title')?>" title="<?=$this->translate('box_mzk_title')?>"></h2>
                            <?=$this->translate('box_mzk_text')?>
                        </div>
                        <div class="card-footer">
                            <p class="mb-0">
                                <a class="btn btn-success text-uppercase" href="/registration/userForm" title="<?=$this->translate('btn_register_title')?>"><?=$this->translate('btn_preregister')?></a>
                            </p>
                        </div>
                    </div>
                </div>
                <!-- /MZK -->

                <!-- BrnoiD -->
                <?php if ($this->brnoIdEnabled) : ?>
                    <div class="col text-center mb-3">
                        <div class="card h-100 border-0 rounded-pill card-brnoid">
                            <div class="card-body">
                                <p class="h6"><?=$this->translate('box_brnoid_head')?></p>
                                <h2 class="heading-logo"><img src="<?=$this->basePath('img/logo-brnoid.svg')?>" alt="<?=$this->translate('box_brnoid_title')?>" title="<?=$this->translate('box_brnoid_title')?>"></h2>
                                <?=$this->translate('box_brnoid_text')?>
                            </div>
                            <div class="card-footer">
                                <p class="mb-0">
                                    <a class="btn btn-success text-uppercase" href="<?=$this->escapeHtmlAttr($this->baseUrl)?>/Shibboleth.sso/DS?entityID=<?=urlencode($this->brnoid)?>&target=<?=urlencode($this->baseUrl)?>/registration/userForm%3Fidp%3Dbrnoid" title="<?=$this->translate('btn_register_title')?>"><?=$this->translate('btn_register')?></a>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- /BrnoiD -->

                <!-- eduID -->
                <?php if ($this->eduIdEnabled) : ?>
                    <div class="col text-center mb-3">
                        <form class="h-100" method="get" action="/Shibboleth.sso/DS">
                            <div class="card h-100 border-0 rounded-pill card-eduid">
                                <div class="card-body">
                                    <input type="hidden" name="target" value="<?=$this->escapeHtmlAttr($this->baseUrl)?>/registration/userForm?idp=eduid"/>
                                    <p class="h6"><?=$this->translate('box_eduid_head')?></p>
                                    <p class="select-university">
                                        <select class="selectpicker" data-width="100%" data-style="btn-light" name="entityID">
                                            <option data-content='<img class="selectpicker-img" src="https://cdn.muni.cz/Css/_Shared/Favicons/000000.ico"> <?=$this->translate('Masaryk University')?>' value="https://idp2.ics.muni.cz/idp/shibboleth" selected></option>
                                        </select>
                                    </p>
                                    <?=$this->translate('box_eduid_text')?>
                                </div>
                                <div class="card-footer">
                                    <p class="mb-0">
                                        <input class="btn btn-success text-uppercase" type="submit" value="<?=$this->translate('btn_register')?>"/>
                                    </p>
                                </div>
                            </div>
                        </form>
                    </div>
                <?php endif; ?>
                <!-- /eduID -->

                <!-- mojeID -->
                <div class="col text-center mb-3">
                    <div class="card h-100 border-0 rounded-pill card-mojeid">
                        <div class="card-body">
                            <p class="h6"><?=$this->translate('box_mojeid_head')?></p>
                            <h2 class="heading-logo"><img src="<?=$this->basePath('img/logo-mojeid.svg')?>" alt="<?=$this->translate('box_mojeid_title')?>" title="<?=$this->translate('box_mojeid_title')?>"></h2>
                            <?=$this->translate('box_mojeid_text')?>
                        </div>
                        <div class="card-footer">
                            <p class="mb-0">
                                <a class="btn btn-success text-uppercase" href="<?=$this->escapeHtmlAttr($this->baseUrl)?>/Shibboleth.sso/DS?entityID=<?=urlencode($this->mojeid)?>&target=<?=urlencode($this->baseUrl)?>/registration/userForm%3Fidp%3Dmojeid" title="<?=$this->translate('btn_register_title')?>"><?=$this->translate('btn_register')?></a>
                            </p>
                        </div>
                    </div>
                </div>
                <!-- /mojeID -->

            </div>
        </div>
    </section>

</div>
