<div>
    <ul>
        <li>
            <a href="/registration/userForm">Vyplnit formulář</a>
        </li>
        <li>
            <a href="https://registrace.mzk.cz/Shibboleth.sso/DS?entityID=https://mojeid.regtest.nic.cz/saml/idp.xml&target=/registration/userForm%3Fidp%3Dmojeid">Vyplnit formulář s převzetím údajů z MojeID</a>
        </li>
        <li>
            <a href="/registration/userForm">Vyplnit formulář s převzetím údajů z BrnoID</a>
        </li>
        <li>
            <a href="/registration/userForm?idp=test">Test</a>
        </li>
    </ul>
</div>