<?php
/**
 * @var Registration\Form\UserForm $form
 */
?>
<script>
config = <?= json_encode($this->config, JSON_PRETTY_PRINT); ?>;
translations = <?= json_encode($this->translations, JSON_PRETTY_PRINT); ?>;

$(document).ready(function() {
  // University/High school selection
  const discountSelect = $('select[name="user[discount]"]');
    discountSelect.change(function() {
    const university = $("#groupUniversity");
    if ($(this).val() == 'UNIVERSITY_STUDENT' || $(this).val() == 'UNOB') {
      university.show();
    } else {
      university.hide();
    }
  });
  discountSelect.change();

  $('select[name="user[discount]"]').change(function() {
    selected = $(this).find(':selected');
    price = selected.data('price');
    $('#price').text(price);
    online = selected.data('online');
    price = selected.data('price');
    proof = selected.data('proof');
    $('#age_not_valid').hide();
    $('#online_free').hide();
    $('#online_discount').hide();
    $('#not_online_for_free_proof').hide();
    $('#not_online_for_free').hide();
    $('#not_online_discount_proof').hide();
    $('#not_online_discount').hide();
    if (selected.length == 0) {
      $('#age_not_valid').show();
    } else if (online && price == 0) {
      $('#online_free').show();
    } else if (online) {
      $('#online_discount').show();
    } else if (price == 0 && proof) {
      $('#not_online_for_free_proof').show();
    } else if (price == 0) {
      $('#not_online_for_free').show();
    } else if (proof) {
      $('#not_online_discount_proof').show();
    } else {
      $('#not_online_discount').show();
    }
  });

  $('select[name="permanentAddress[country]"]').change(function() {
    country = $(this).val();
    icOption = $("select[name='user[identificationType]'] option[value='IC']");
    passportOption = $("select[name='user[identificationType]'] option[value='PAS']");
    if (country == 'CZ') {
      icOption.show().prop('selected', true);
      passportOption.hide();
    } else if (config.countries.EU.includes(country)) {
      icOption.show().prop('selected', true);
      passportOption.show();
    } else {
      icOption.hide();
      passportOption.show().prop('selected', true);
    }
  });
  $('select[name="permanentAddress[country]"]').change();

  $('select[name="user[university]"]').change(function() {
    $('#online_muni').hide();
    group = $("option:selected", this).parent()[0].id;
    verified = $("input[name='verified'").val();
    if (group == 'muni' && verified == 'false') {
      $('#online_muni').show();
    }
  });
  $('select[name="user[university]"]').change();

  $('input[name="password[password]"]').focusout(function() {
    password = $(this).val();
    jQuery.ajax({
      url: "/ajax/validatePassword",
      type: "POST",
      data: {'password' : password },
      dataType: "json",
      contentType: "application/x-www-form-urlencoded; charset=utf-8",
      success: function (data, textStatus) {
        // reset previous errors
        $('#userForm :input[name="password[password]"]').removeClass('is-invalid');
        $('#userForm :input[name="password[password]"]').parent().find('ul').remove();
        if (data['status'] == 'ok') {
          return;
        }
        input = $('#userForm :input[name="password[password]"]');
        input.addClass('is-invalid');
        ul = $('<ul/>');
        ul.attr({'class': 'form-text error'});
        $.each(data['messages'], function(index, error) {
          li = $('<li/>');
          li.text(error);
          ul.append(li);
        });
        input.parent().append(ul);
      }
    });
  });

  $('input[name="password[passwordConfirm]"]').focusout(function() {
    password = $('input[name="password[password]"]').val();
    passwordConfirm = $(this).val();
    $(this).removeClass('is-invalid');
    $(this).parent().find('ul').remove();
    if (password == passwordConfirm) {
      return;
    }
    $(this).addClass('is-invalid');
    ul = $('<ul/>');
    ul.attr({'class': 'form-text error'});
    li = $('<li/>');
    li.text(translations['userForm_passwordConfirmNoMatch']);
    ul.append(li);
    $(this).parent().append(ul);
  });

  $(':input[name="user[birth][day]"], :input[name="user[birth][month]"], :input[name="user[birth][year]"], ' +
    ':input[name="user[idsJmk]"]').change(function() {
    selected = $('select[name="user[discount]"]').val();
    selectedGroup = $('select[name="user[discount]"]').find(':selected').data('group')
    params = $("#userForm").serialize();
    jQuery.ajax ({
      url: "/ajax/discount",
      type: "POST",
      data: params,
      dataType: "json",
      contentType: "application/x-www-form-urlencoded; charset=utf-8",
      success: function(data, textStatus) {
        $options = $('select[name="user[discount]"]').children().remove().end();
        selectedOption = null;
        if (data.length == 0) {
          $('select[name="user[discount]"]').change();
          return;
        }
        $.each(data, function(key, obj) {
          option = $('<option/>');
          if (selectedOption == null || selected == key || selectedGroup == obj['group']) {
              selectedOption = option;
          }
          option.attr({ 'value': key, 'data-price': obj['price'], 'data-group' : obj['group'],
            'data-online': obj['online'], 'data-proof': obj['proof'] }).text(obj['label']);
          $options.append(option);
        });
        selectedOption.attr({'selected': ''});
        $('select[name="user[discount]"]').change();
      }
    });
  });
  $('select[name="user[birth][day]"]').change();

  $("#userForm").submit(function(event) {
    event.preventDefault();
    params = $("#userForm").serialize();
    $('#userForm :submit').attr('disabled', 'true');
    jQuery.ajax ({
      url: "/ajax/validate",
      type: "POST",
      data: params,
      dataType: "json",
      contentType: "application/x-www-form-urlencoded; charset=utf-8",
      success: function(data, textStatus) {
        $('#userForm :submit').removeAttr('disabled');
        // reset previous errors
        $('#userForm :input').removeClass('is-invalid');
        $('#userForm li').parent().remove();
        // if validation is OK, submit the form
        if (data['status'] == 'ok') {
          $("#userForm").unbind('submit');
          $("#userForm :submit").click();
          return;
        }
        // fill new errors
        $.each(data, function(key, errors) {
          if (key == 'user[birth]') {
            key = 'user[birth][year]';
          }
          input = $('#userForm :input[name=\'' + key + '\']');
          input.addClass('is-invalid');
          ul = $('<ul/>');
          ul.attr({'class': 'form-text error'});
          $.each(errors, function(index, error) {
            li = $('<li/>');
            li.text(error);
            ul.append(li);
          });
          input.parent().append(ul);
        });
        // set focus on first found error
        $('#userForm :input.is-invalid').first().focus();
      },
      error : function(data, textStatus) {
        // submit the form manually and use server side validation
        $('#userForm :submit').removeAttr('disabled');
        $("#userForm").unbind('submit');
        $("#userForm :submit").click();
      }
    });
  });

});
</script>

<?=$this->render('steps.phtml', ['step' => 1]) ?>

<section>
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <?php if ($this->unverified): ?>
                    <div class="alert alert-danger">
                        <?= $this->translate('unverified_account') ?>
                    </div>
                <?php endif; ?>
                <?php
                $form->prepare();
                ?>
                <?= $this->form()->openTag($form); ?>
                <div class="card">
                    <h2 class="card-header">
                        <?= $this->translate('text_personal_information') ?>
                    </h2>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-2">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('degree')])?>
                            </div>
                            <div class="col-md-5">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('firstName')])?>
                            </div>
                            <div class="col-md-5">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('lastName')])?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('phone')])?>
                            </div>
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('email')])?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('birth')])?>
                            </div>
                            <div class="col-md-12" style="display: none">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('idsJmk')])?>
                            </div>
                            <div class="col-md-12">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('discount')])?>
                            </div>
                            <div class="col-md-12">
                                <div id="age_not_valid" class="alert alert-danger" style="display: none;">
                                    <?=$this->translate('userForm_ageNotValid')?>
                                </div>
                                <div id="online_free" class="alert alert-success" style="display: none;">
                                    <?=$this->translate('online_for_free')?>
                                </div>
                                <div id="online_discount" class="alert alert-success" style="display: none;">
                                    <?=$this->translate('online_discount')?>
                                </div>
                                <div id="not_online_for_free_proof" class="alert alert-warning" style="display: none;">
                                    <?=$this->translate('not_online_for_free_proof')?>
                                </div>
                                <div id="not_online_for_free" class="alert alert-warning" style="display: none;">
                                    <?=$this->translate('not_online_for_free')?>
                                </div>
                                <div id="not_online_discount_proof" class="alert alert-warning">
                                    <?=$this->translate('not_online_discount_proof')?>
                                </div>
                                <div id="not_online_discount" class="alert alert-warning">
                                    <?=$this->translate('not_online_discount')?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12" id="groupUniversity">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('university')])?>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div id="online_muni" class="alert alert-warning" style="display: none;">
                                <?=$this->translate('online_muni_registration')?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h2 class="card-header"><?=$this->translate('text_address')?></h2>
                    <div class="card-body">
                        <h4><?=$this->translate('text_permanent_address')?></h4>
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('street')])?>
                            </div>
                            <div class="col-md-4">
                                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('city')])?>
                            </div>
                            <div class="col-md-2">
                                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('postcode')])?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('country')])?>
                            </div>
                        </div>

                        <?=$this->render('element.phtml', ['element' => $form->get('user')->get('isContactAddress')])?>

                        <div id="collapseisContactAddress" class="panel-collapse collapse in">
                            <h4><?=$this->translate('text_contact_address')?></h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('street')])?>
                                </div>
                                <div class="col-md-4">
                                    <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('city')])?>
                                </div>
                                <div class="col-md-2">
                                    <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('postcode')])?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h2 class="card-header"><?=$this->translate('Doklad totožnosti')?></h2>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('identificationType')])?>
                            </div>
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('identification')])?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h2 class="card-header"><?= $this->translate('text_password') ?></h2>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('password')->get('password')])?>
                            </div>
                            <div class="col-md-6">
                                <?=$this->render('element.phtml', ['element' => $form->get('password')->get('passwordConfirm')])?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <?=$this->render('element.phtml', ['element' => $form->get('isSendNews')])?>
                    <?=$this->render('element.phtml', ['element' => $form->get('isGdpr')])?>
                </div>

                <?=$this->formElement($form->get('verified'))?>
                <?=$this->formElement($form->get('discountEntitlement'))?>

                <div class="alert alert-primary text-center">
                    Cena registrace je <strong><span id="price">XXX</span>,- Kč</strong>
                </div>
                <div class="text-center">
                    <input type="submit" name="submit" class="btn btn-primary" value="<?=$this->translate('btn_submit_registration') ?> &raquo;">
                </div>
                <?=$this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>

