<?php
/**
* @var \Laminas\Form\Element $element
*/
?>
<? if ($element instanceof \Laminas\Form\Element) : ?>
  <?php
  $options = $element->getOptions();
  $labelClass = 'form-label';
  $required = isset($options['required']) && $options['required'];
  if ($required) {
    $labelClass .= ' required';
  }
  $element->setLabelAttributes(['class' => $labelClass]);
  $element->setAttribute('class', 'form-control');
  $element->setAttribute('id', $element->getName());
  ?>
  <div class="mb-3<?= $required ? ' required' : '' ?>">
    <?= $this->formLabel($element) ?>
    <?= $this->formElement($element) ?>
    <?= $this->formElementErrors()->render($element, ['class' => 'form-text']) ?>
  </div>
<? endif; ?>
