<?php
/**
* @var \Laminas\Form\Element|\Laminas\Form\Element\DateSelect $element
*/
?>
<? if ($element instanceof \Laminas\Form\Element): ?>
    <? if ($element instanceof \Laminas\Form\Element\DateSelect): ?>
        <?php
        $options = $element->getOptions();
        $labelClass = 'form-label';
        $required = isset($options['required']) && $options['required'];
        if ($required) {
            $labelClass .= ' required';
        }
        $element->setLabelAttributes(['class' => $labelClass]);
        $element->setAttribute('class', 'form-control');
        $element->setAttribute('id', $element->getName());
        ?>
        <div class="form-group">
            <?//= $this->formLabel($element) ?>
            <label class="form-label<?= $required ? ' required' : '' ?>" for="<?= $element->getName() ?>">
                <?=$this->translate($element->getLabel()); ?>:<?= $required ? '*' : null ?>
            </label>
            <div>
                <?= $this->formElement($element) ?>
                <?= $this->formElementErrors()->render($element, ['class' => 'form-text']) ?>
            </div>
        </div>
    <? elseif ($element instanceof \Laminas\Form\Element\Checkbox): ?>
        <div class="form-group">
            <?= $this->formElement($element) ?>
            <?= $this->formLabel($element) ?>
        </div>
    <? else: ?>
        <?php
        $options = $element->getOptions();
        $labelClass = 'form-label';
        $required = isset($options['required']) && $options['required'];
        if ($required) {
            $labelClass .= ' required';
        }
        $element->setLabelAttributes(['class' => $labelClass]);
        $element->setAttribute('class', 'form-control');
        $element->setAttribute('id', $element->getName());
        ?>
        <div class="form-group<?= $required ? ' required' : '' ?>">
            <?//= $this->formLabel($element) ?>
            <label class="form-label<?= $required ? ' required' : '' ?>" for="<?= $element->getName() ?>">
                <?=$this->translate($element->getLabel()); ?>:<?= $required ? '*' : null ?>
            </label>
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors()->render($element, ['class' => 'form-text']) ?>
        </div>
    <? endif; ?>
<? endif; ?>
