<?php
/**
 * @var Registration\Form\UserForm $form
 */
?>
<script>
$(document).ready(function() {
  // University/High school selection
  studySelect = $('select[name="user[study]"]');
  studySelect.change(function() {
    highSchool = $("div.form-group").has("select[name='user[highSchool]'");
    university = $("div.form-group").has("select[name='user[university]'");
    val = $(this).val();
    if (val == 'UN') {
        highSchool.hide();
        university.show();
    } else if (val == 'HS') {
        highSchool.show();
        university.hide();
    } else {
        highSchool.hide();
        university.hide();
    }
  });
  studySelect.change();

  // Input validation
  requiredInput = $("div.required").find("input");
  requiredInput.blur(function() {
    value = $(this).val();
    if (value.trim() === "") {
      $(this).addClass('is-invalid');
      $(this).removeClass('is-valid');
    } else {
      $(this).removeClass('is-invalid');
      $(this).addClass('is-valid');
    }
  });
  requiredInput.blur();
});
</script>

<ul class="nav mb-3">
    <li class="mr-3">
        <a class="btn btn-primary active"><?=$this->translate('Personal information')?></a>
    </li>
    <li class="mr-3">
        <a class="btn btn-outline-primary" href="<?=$this->url('password')?>"><?=$this->translate('Password')?></a>
    </li>
</ul>

<?
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>

<div class="card">
    <h2 class="card-header">
        <?= $this->translate('Personal information') ?>
    </h2>
    <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('degree')])?>
            </div>
            <div class="col-md-5">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('firstName')])?>
            </div>
            <div class="col-md-5">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('lastName')])?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('email')])?>
            </div>
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('phone')])?>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('identificationType')])?>
            </div>
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('identification')])?>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('birth')])?>
            </div>
            <div class="col-md-12">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('study')])?>
            </div>
            <div class="col-md-12">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('highSchool')])?>
            </div>
            <div class="col-md-12">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('university')])?>
            </div>
            <div class="col-md-12">
                <?=$this->render('element.phtml', ['element' => $form->get('user')->get('discount')])?>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <h2 class="card-header"><?= $this->translate('Permanent address') ?></h2>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('street')])?>
            </div>
            <div class="col-md-4">
                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('city')])?>
            </div>
            <div class="col-md-2">
                <?=$this->render('element.phtml', ['element' => $form->get('permanentAddress')->get('postcode')])?>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <h2 class="card-header"><?= $this->translate('Contact address') ?></h2>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('street')])?>
            </div>
            <div class="col-md-4">
                <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('city')])?>
            </div>
            <div class="col-md-2">
                <?=$this->render('element.phtml', ['element' => $form->get('contactAddress')->get('postcode')])?>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <?= $this->formSubmit($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag(); ?>
