<?php
/**
 * @var Registration\Form\UserForm $form
 */
?>
<script>
$(document).ready(function() {
  // University/High school selection
  studySelect = $('select[name="user[study]"]');
  studySelect.change(function() {
    highSchool = $("div.form-group").has("select[name='user[highSchool]'");
    university = $("div.form-group").has("select[name='user[university]'");
    val = $(this).val();
    if (val == 'UN') {
        highSchool.hide();
        university.show();
    } else if (val == 'HS') {
        highSchool.show();
        university.hide();
    } else {
        highSchool.hide();
        university.hide();
    }
  });
  studySelect.change();

  // Input validation
  requiredInput = $("div.required").find("input");
  requiredInput.blur(function() {
    value = $(this).val();
    if (value.trim() === "") {
      $(this).addClass('is-invalid');
      $(this).removeClass('is-valid');
    } else {
      $(this).removeClass('is-invalid');
      $(this).addClass('is-valid');
    }
  });
  requiredInput.blur();
});
</script>
<?
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<h2><?= $this->translate('Personal information') ?></h2>
<? foreach($form->get('user') as $element): ?>
   <?=$this->render('registration/index/element.phtml', ['element' => $element])?>
<? endforeach; ?>
<h2><?= $this->translate('Permanent address') ?></h2>
<? foreach($form->get('permanentAddress') as $element): ?>
    <?=$this->render('registration/index/element.phtml', ['element' => $element])?>
<? endforeach; ?>
<h2><?= $this->translate('Contact address') ?></h2>
<? foreach($form->get('contactAddress') as $element): ?>
    <?=$this->render('registration/index/element.phtml', ['element' => $element])?>
<? endforeach; ?>
<h2><?= $this->translate('Password') ?></h2>
<? foreach($form->get('password') as $element): ?>
    <?=$this->render('registration/index/element.phtml', ['element' => $element])?>
<? endforeach; ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
