<?php
/**
 * @var Registration\Form\UserForm $form
 */
?>
<script>
$(document).ready(function() {
  // Input validation
  requiredInput = $("div.required").find("input");
  requiredInput.blur(function() {
    value = $(this).val();
    if (value.trim() === "") {
      //$(this).addClass('is-invalid');
      //$(this).removeClass('is-valid');
    } else {
      //$(this).removeClass('is-invalid');
      //$(this).addClass('is-valid');
    }
  });
  requiredInput.blur();
});
</script>

<ul class="nav mb-3">
    <li class="mr-3">
        <a class="btn btn-outline-primary" href="<?=$this->url('registration')?>"><?=$this->translate('text_personal_information')?></a>
    </li>
    <li class="mr-3">
        <a class="btn btn-primary active"><?=$this->translate('text_password')?></a>
    </li>
</ul>

<?
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>

<div class="card">
    <h2 class="card-header"><?= $this->translate('text_password') ?></h2>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('password')->get('password')])?>
            </div>
            <div class="col-md-6">
                <?=$this->render('element.phtml', ['element' => $form->get('password')->get('passwordConfirm')])?>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
     <a class="btn btn-secondary" href="<?=$this->url('registration')?>">&laquo; <?= $this->translate('btn_back'); ?></a>
    <?//= $this->formSubmit($form->get('submit')); ?>
    <input type="submit" name="submit" class="btn btn-primary" value="<?=$this->translate('btn_submit_registration');?> &raquo;">

</div>

<?= $this->form()->closeTag(); ?>
