<?php
switch ($this->step) {
    case 1:
        $step1 = true;
        $step2 = false;
        $step3 = false;
        break;
    case 2:
        $step1 = true;
        $step2 = true;
        $step3 = false;
        break;
    case 3:
        $step1 = true;
        $step2 = true;
        $step3 = true;
        break;
}
?>
<section class="steps">
    <div class="container">
        <div class="steps d-flex flex-wrap flex-sm-nowrap justify-content-between padding-top-2x padding-bottom-1x">
            <div class="step<?php
            if ($step1): ?> completed<?php
            endif; ?>">
                <div class="step-icon-wrap">
                    <div class="step-icon">1</div>
                </div>
                <h4><?=$this->translate('step_1_text')?></h4>
            </div>
            <div class="step<?php
            if ($step2): ?> completed<?php
            endif; ?>">
                <div class="step-icon-wrap">
                    <div class="step-icon">2</div>
                </div>
                <h4><?=$this->translate('step_2_text')?></h4>
            </div>
            <div class="step<?php
            if ($step3): ?> completed<?php
            endif; ?>">
                <div class="step-icon-wrap">
                    <div class="step-icon">3</div>
                </div>
                <h4><?=$this->translate('step_3_text')?></h4>
            </div>
        </div>
    </div>
</section>
