<?=$this->render('steps.phtml', ['step' => 3]) ?>

<section class="thank-mzk py-5 bg-info-light">
    <div class="container">

        <div class="row">
            <div class="col-md-5 d-none d-md-block d-lg-block d-xl-block text-center">
                <div class="pr-3">
                    <img class="img-fluid" src="<?=$this->basePath('img/mzk.png')?>" alt="">
                </div>
            </div>
            <div class="col-md-7 align-self-center">
                <h1>Děkujeme, že jste si vybrali Moravskou zemskou knihovnu!</h1>

                <p><strong>Pro dokončení registrace navštivte nejpozději do 14 dní</strong> knihovnu.<br>
                    V půjčovně v přízemí vám bude po ověření totožnosti vystavena čtenářská průkazka.<br>
                    Zde také můžete zaplatit registrační poplatek v hotovosti.</p>

                <p class="mb-0">
                    Nezapomeňte s sebou:
                </p>
                <ul>
                    <li><strong>doklad totožnosti</strong></li>
                    <li>případně <strong>doklad potvrzující nárok na vaši slevu</strong></li>
                </ul>
                <p>
                    Již nyní si můžete vybírat a objednávat knihy z našeho <a href="https://vufind.mzk.cz/" target="_blank" title="Vyhledávání v katalogu MZK">katalogu</a>.
                </p>

                <p>Těšíme se na Vaši návštěvu!</p>

            </div>
        </div>

    </div>
</section>

