<?=$this->render('steps.phtml', ['step' => 3])?>

<section class="thank-mzk py-5 bg-info-light">
    <div class="container">

        <div class="row">
            <div class="col-md-5 d-none d-md-block d-lg-block d-xl-block text-center">
                <div class="pr-3">
                    <img class="img-fluid" src="<?=$this->basePath('img/mzk.png')?>" alt="">
                </div>
            </div>
            <div class="col-md-7 align-self-center">
                <h1><?=$this->translate('text_finished_head')?></h1>

                <p><?=sprintf($this->translate('text_temporary_login'), $this->login)?></p>
                <p><?=$this->translate('text_payment_finished')?></p>
                <p><?=$this->translate('text_looking_forward')?></p>
                <?=$this->translate('text_close_browser')?>
            </div>
        </div>

    </div>
</section>

<section class="py-5">
    <div class="container">
        <h2 class="text-center mb-4"><?=$this->translate('text_available_services')?></h2>

        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-5">
            <!-- database -->
            <div class="col text-center mb-3">
                <div class="card h-100 border-0 rounded-pill box-purple">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/database.png')?>" alt="Elektronické informační zdroje">
                        </p>
                        <p class="my-4">
                            <?=$this->translate('text_remote_access_books')?>
                        </p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-purple" href="https://www.mzk.cz/katalogy-databaze/databaze#tab1" title=""><?=$this->translate('btn_explore')?></a>
                    </div>
                </div>
            </div>
            <!-- /database -->
            <!-- digital library -->
            <div class="col text-center mb-3">
                <div class="card h-100 border-0 rounded-pill box-blue">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/digitallibrary.png')?>" alt="Vzdálený přístup">
                        </p>
                        <p class="my-4">
                            <?=$this->translate('text_remote_access_db')?>
                        </p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-blue" href="https://dnnt.mzk.cz/" title=""><?=$this->translate('btn_explore')?></a>
                    </div>
                </div>
            </div>
            <!-- /digital library -->
            <!-- catalog -->
            <div class="col text-center mb-3">
                <div class="card h-100 border-0 rounded-pill box-cyan">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/catalog.png')?>" alt="Katalog MZK">
                        </p>
                        <p class="my-4">
                            <?=$this->translate('text_remote_catalog')?>
                        </p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-cyan" href="https://vufind.mzk.cz/" title=""><?=$this->translate('btn_explore')?></a>
                    </div>
                </div>
            </div>
            <!-- /catalog -->
        </div>
    </div>
</section>
