<?=$this->render('steps.phtml', ['step' => 3]) ?>

<section>
    <div class="container">
        <div>
            <p>
                Těší nás, že jste stal/a čtenářem/čtenářkou Moravské zemské knihovny!
            </p>
            <p>
                <strong>Pro dokončení registrace navštivte nejpozději do 14 dnů knihovnu.</strong><br>
                V půjčovně v přízemí vám bude po ověření totožnosti vystavena čtenářská průkazka.
            </p>
            <p class="mb-0">
                Nezapomeňte s sebou:
            </p>
            <ul>
                <li><strong>doklad totožnosti</strong></li>
                <li>případně <strong>doklad potvrzující nárok na vaši slevu</strong></li>
            </ul>
            <p>
                Již nyní si můžete vybírat a objednávat knihy z našeho <a href="https://vufind.mzk.cz/" target="_blank" title="Vyhledávání v katalogu MZK">katalogu</a>.
            </p>
            <p>
                Těšíme se na vaši návštěvu.
            </p>
        </div>
    </div>
</section>
