<?=$this->render('steps.phtml', ['step' => 3]) ?>

<section class="thank-mzk py-5 bg-info-light">
    <div class="container">

        <div class="row">
            <div class="col-md-5 d-none d-md-block d-lg-block d-xl-block text-center">
                <div class="pr-3">
                    <img class="img-fluid" src="<?=$this->basePath('img/mzk.png')?>" alt="">
                </div>
            </div>
            <div class="col-md-7 align-self-center">
                <h1><?=$this->translate('text_finished_head')?></h1>
                <?=$this->translate('text_payment_finished_cash')?>
                <?=$this->translate('text_close_browser')?>
            </div>
        </div>

    </div>
</section>

