<?=$this->render('steps.phtml', ['step' => 3])?>

<section class="thank-mzk py-5">
    <div class="container-fluid">

        <div class="row">
            <div class="col-lg-5 col-xl-5">
                <img class="img-fluid" src="<?=$this->basePath('img/mzk.png')?>" alt="">
            </div>
            <div class="col-lg-6 offset-lg-1 col-xl-6 offset-xl-1">
                <h1>Děkujeme, že jste si vybrali Moravskou zemskou knihovnu!</h1>

                <p>Pro vystavení čtenářské průkazky, nutné pro fyzické výpůjčky, navštivte půjčovnu v přízemí knihovny.</p>

                <p>Těšíme se na Vaši návštěvu!</p>

            </div>
        </div>

    </div>
</section>

<section class="py-5">
    <div class="container-fluid">
        <p class="h1 text-center mb-5">Již nyní můžete z pohodlí domova využívat následující služby:</p>

        <div class="row">
            <!-- database -->
            <div class="col-md-6 col-lg-4 text-center">
                <div class="card border-0 rounded-pill box-purple">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/database.png')?>" alt="Elektronické informační zdroje">
                        </p>
                        <p class="my-4">
                            Vzdálený přístup do vybraných elektronických informačních zdrojů
                        </p>
                        <p>
                            <a class="btn btn-purple" href="#" title="">Prozkoumat</a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- /database -->
            <!-- digital library -->
            <div class="col-md-6 col-lg-4 text-center">
                <div class="card border-0 rounded-pill box-blue">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/digitallibrary.png')?>" alt="Vzdálený přístup">
                        </p>
                        <p class="my-4">
                            Vzdálený přístup do databáze digitalizovaných děl nedostupnýých na trhu (včetně autorsky chráněných děl)
                        </p>
                        <p>
                            <a class="btn btn-blue" href="#" title="">Prozkoumat</a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- /digital library -->
            <!-- catalog -->
            <div class="col-md-6 col-lg-4 text-center">
                <div class="card border-0 rounded-pill box-cyan">
                    <div class="card-body">
                        <p>
                            <img class="img-fluid" src="<?=$this->basePath('img/catalog.png')?>" alt="Katalog MZK">
                        </p>
                        <p class="my-4">
                            Současně si již také můžete vybírat a objednávat knihy z našeho katalogu.
                        </p>
                        <p>
                            <a class="btn btn-cyan" href="#" title="">Prozkoumat</a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- /catalog -->
        </div>
    </div>
</section>
