<div>
    <p>
        Děkujeme, že jste si vybrali Moravskou zemskou knihovnu!
    </p>
    <p>
        <strong>Pro dokončení registrace navštivte nejpozději do 14 dní knihovnu.</strong><br>
        V půjčovně v přízemí vám bude po ověření totožnosti vystavena čtenářská průkazka.
    </p>
    <p class="mb-0">
        Nezapomeňte s sebou:
    </p>
    <ul>
        <li><strong>doklad totožnosti</strong></li>
        <li>případně <strong>doklad potvrzující nárok na vaši slevu</strong></li>
    </ul>
    <p>
        Již nyní si můžete vybírat a objednávat knihy z našeho <a href="https://vufind.mzk.cz/" target="_blank" title="Vyhledávání v katalogu MZK">katalogu</a>.
    </p>
    <p>
        Těšíme se na Vaši návštěvu.
    </p>
</div>
