<?=$this->render('steps.phtml', ['step' => 3]) ?>

<section>
    <div class="container">
        <div>
            <p>
                Těší nás, že jste stal/a čtenářem/čtenářkou Moravské zemské knihovny!
            </p>
            <p class="mb-0">
                Již nyní můžete z pohodlí domova využívat následující služby:
            </p>
            <ul>
                <li>
                    <a href="https://www.mzk.cz/databaze" target="_blank" title="MZK: Databáze">Vzdálený přístup do vybraných elektronických informačních zdrojů</a>
                </li>
                <li>
                    <a href="https://dnnt.mzk.cz" target="_blank" title="Moravská zemská knihovna v Brně | Digitální knihovna Kramerius">Vzdálený přístup do databáze digitalizovaných děl nedostupných na trhu (včetně autorsky chráněných děl)</a>
                </li>
            </ul>
            <p>
                Současně si již také můžete vybírat a objednávat knihy z našeho <a href="https://vufind.mzk.cz/" target="_blank" title="Vyhledávání v katalogu MZK">katalogu</a>.<br>
                Pro vystavení čtenářské průkazky, nutné pro fyzické výpůjčky, navštivte půjčovnu v přízemí knihovny.
            </p>

            <p>
                Těšíme se na vaši návštěvu.
            </p>

        </div>
    </div>
</section>

