<div>
    <p>
        Děkujeme, že jste si vybrali Moravskou zemskou knihovnu!
    </p>
    <p class="mb-0">
        Již nyní můžete z pohodlí domova využívat následující služby:
    </p>
    <ul>
        <li>
            <a href="https://www.mzk.cz/databaze" target="_blank" title="MZK: Databáze">Vzdálený přístup do vybraných elektronických informačních zdrojů</a>
        </li>
        <li>
            <a href="https://dnnt.mzk.cz" target="_blank" title="Moravská zemská knihovna v Brně | Digitální knihovna Kramerius">Vzdálený přístup do databáze digitalizovaných děl nedostupných na trhu (včetně autorsky chráněných děl)</a>
        </li>
    </ul>
    <p>
        Současně si již také můžete vybírat a objednávat knihy z našeho katalogu.<br>
        Pro vystavení čtenářské průkazky, nutné pro fyzické výpůjčky, navštivte půjčovnu v přízemí knihovny.
    </p>

    <p>
        Těšíme se na Vaši návštěvu.
    </p>

</div>
