<section>
    <div class="container">
        <div>
            <h1><?=$this->translate('text_gateway_h1')?></h1>
            <ul>
                <li>
                    <a href="/payment/demoGatewayFinish"><?=$this->translate('text_gateway_success')?></a>
                </li>
                <li>
                    <a href="/payment/refused"><?=$this->translate('text_gateway_denied')?></a>
                </li>
                <li>
                    <a href="/payment/error"><?=$this->translate('text_gateway_fail')?></a>
                </li>
            <ul>
        </div>
    </div>
</section>

