<section>
    <div class="container-fluid">
        <div>
            <h1>Simulace platební brány</h1>
            <ul>
                <li>
                    <a href="/payment/finished">Platba proběhla v pořádku</a>
                </li>
                <li>
                    <a href="/payment/refused">Platba byla zamítnuta</a>
                </li>
                <li>
                    <a href="/payment/error">Platba proběhla s chybou</a>
                </li>
                <ul>
        </div>
    </div>
</section>

