<?=$this->render('steps.phtml', ['step' => 2]) ?>

<section>
    <div class="container">
        <div class="text-center">
            <span class="d-block mb-2"><i class="fa fa-2x fa-exclamation-triangle text-danger"></i></span>
            <p><?= $this->translate('registration_payment_refused') ?></p>
            <p class="mb-5"><a class="btn btn-success text-uppercase" href="#">Opakovat platbu</a></p>
            <p>Chcete změnit <a href="/Registration/finished">způsob platby</a>?</p>
        </div>
    </div>
</section>
